# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3750a3c5f41aa7b0fef500cb6bcc12b7f0555184dc896b45107cf9cd15c34fbe1bc223cf06e80d39228cbde18c5882534e6386ef895372f5a7c9185937d39480

test:
  secret_key_base: 55fb47adbbe35593fee38b43dfdbe4c3d8cc08a492f49853a792aac7c264ffb2367fb551ce94a74cebc9813476b7a6c36ebf1064a1b7ea21ad769e8d56fc66cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
